# tasks file
---

- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml

- name: install | requirements
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
    update_cache: true
  with_items:
    - binutils
    - git

- name: install | pull amazon-efs-utils
  git:
    repo: "{{ aws_efs_utils_repo_url }}"
    dest: "{{ aws_efs_utils_dest_dir }}"
    version: "{{ aws_efs_utils_version }}"
  args:
    creates: "{{ aws_efs_utils_dest_dir }}/build/amazon-efs-utils*deb"

- name: install | build amazon-efs-utils
  command: "{{ aws_efs_utils_dest_dir }}/build-deb.sh"
  args:
    chdir: "{{ aws_efs_utils_dest_dir }}"

- name: install | find amazon-efs-utils built package
  shell: "ls {{ aws_efs_utils_dest_dir }}/build/amazon-efs-utils*deb"
  register: package

- name: install | amazon-efs-utils
  apt:
    deb: "{{ package.stdout }}"

- name: mount | ensure mount directory exists
  file:
    path: "{{ efs_mount_dir }}"
    mode: 0755
    state: directory

- name: mount | ensure EFS volume is mounted
  mount:
    name: "{{ efs_mount_dir }}"
    src: "{{ efs_file_system_id }}"
    fstype: efs
    opts: "{{ efs_mount_opts }}"
    state: "{{ mount_state | default('mounted') }}"
  tags: notest
